### ISSUE TITLE
Few packages missing in package.json

### ISSUE THREAD

**Issue by srivatsansraghavan** [tamjankowska/dream-team#90]

**Comment by nmunro** [comment]
@srivatsansraghavan Thanks for your interest and wanting to help, but this is actually a class group project by my students which has now concluded and they did very well! 

To address your points though as it may be useful as you work on other projects.

1) React is installed as part of the project, just not in the package.json file that is to do with the server, you can find the front end dependencies in the package.json associated with the front end: https://github.com/tamjankowska/dream-team/blob/main/frontend/package.json

There is an `npm run bootstrap` command that will install the dependencies for both aspects.

2) Regarding your unhandled promise rejection, the project uses dot-env, a package for hiding sensitive information from public view (like database urls, login details etc) https://github.com/tamjankowska/dream-team/blob/38a74d33af97a796151ac31c298c86491a73b837/package.json#L29 the app will not run without a `.env` file but these are obviously not committed to git for security reasons.

You can see here: https://github.com/tamjankowska/dream-team/blob/38a74d33af97a796151ac31c298c86491a73b837/index.js#L18 where the process.env object is being used to pull the environmental variables out of the .env file.

Hope that helps :)

**Comment by srivatsansraghavan** [comment]
Thanks a lot @nmunro .
This helped me understand what I was missing while trying to run this in localhost.
